### ISSUE TITLE
Warp Layer Tests

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig-tests-regressions#14]
Add tests for Warp Layer (https://wiki.synfig.org/Warp_Layer) to ```sources/layers/warp```.

We need to test following configurations:

1. Warp Layer on top of Checkerboard Layer (https://wiki.synfig.org/Checkerboard_Layer, representing single-point perspective. Like this: 

![screenshot_002](https://user-images.githubusercontent.com/332868/48670118-d04fe300-eb44-11e8-8d63-67fda0428a15.png)

(notice two edges of distortion box are parallel)

2. Warp Layer on top of Checkerboard Layer (https://wiki.synfig.org/Checkerboard_Layer, representing two-point perspective. Like this: 

![screenshot_003](https://user-images.githubusercontent.com/332868/48670120-dba30e80-eb44-11e8-9056-35b24ff46b2b.png)

Both configurations should be represented with the following parameter variations:

* Clip: 
   * on (default)
   * off
* Horizon:
   * 2.0
   * 4.0

It is expected to have filenames like this:

* **warp-checkerboard-1point-horizon-2.sif** - single-point perspective with Clip=on (default) and Horizon = 2.0
* **warp-checkerboard-1point-horizon-4.sif** - single-point perspective with Clip=on and Horizon = 4.0
* **warp-checkerboard-1point-noclip-horizon-2.sif** - single-point perspective with Clip=off and Horizon = 2.0
* **warp-checkerboard-1point-noclip-horizon-4.sif** - ...
* **warp-checkerboard-2point-horizon-2.sif** - two-point perspective with Clip=on and Horizon = 2.0
* **warp-checkerboard-2point-horizon-4.sif** - ...
* **warp-checkerboard-2point-noclip-horizon-2.sif** - ...
* **warp-checkerboard-2point-noclip-horizon-4.sif** - ...

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#1

**Comment by morevnaproject** [comment]
Done by https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/30
