### ISSUE TITLE
Linear Gradient Tests

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig-tests-regressions#15]
Add tests for Linear Gradient Layer (https://wiki.synfig.org/Linear_Gradient_Layer) to ```sources/layers/gradient-linear```.

We need several tests with some key color combinations:
```
gradient-linear-black-white.sif
gradient-linear-blue-yellow.sif
gradient-linear-blue-black.sif
gradient-linear-blue-white.sif
gradient-linear-red-black.sif
gradient-linear-red-white.sif
gradient-linear-red-alpha.sif
```

And also some tests for "Loop" and "ZigZag" parameters (and their combinations):

```
gradient-linear-black-white-loop.sif
gradient-linear-black-white-zigzag.sif
gradient-linear-black-white-loop-zigzag.sif
```

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#2

**Comment by morevnaproject** [comment]
Closed by https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/16
