### ISSUE TITLE
Curve Gradient Tests

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig-tests-regressions#16]
There are 7 sample tests in ```sources/layers/gradient-curve/```, which represent tests of Curve Gradient Layer (https://wiki.synfig.org/Curve_Gradient_Layer) for 7 different shapes:

```
gradient-curve-shape1-width-25.sif
gradient-curve-shape2-width-25.sif
gradient-curve-shape3-width-25.sif
gradient-curve-shape4-width-25.sif
gradient-curve-shape5-width-25.sif
gradient-curve-shape6-width-25.sif
gradient-curve-shape7-width-25.sif
```

It is required to create a set of sub-tests for each shape type with variations for the following parameters:

* Width:
   * 0
   * 0.25px
   * 1px
   * 10px
   * 60px
   * 250px
* Loop
   * On
* ZigZag
   * On
* Perpendicular
   * On
* Fast:
   * Off

It is expected to have filenames like this:

```
gradient-curve-shape1-width-0.25.sif
gradient-curve-shape1-width-60.sif
gradient-curve-shape1-width-25-zigzag.sif
gradient-curve-shape1-width-25-nofast.sif
...
```

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#3

**Comment by morevnaproject** [comment]
Closed with https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/14
