### ISSUE TITLE
Blur Layer Tests

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#17]
Add more tests for Blur Layer (https://wiki.synfig.org/Blur_Layer) to sources/layers/blur.

Initially  add Star Layer from Layer > New Layer > Geometry > Star

Then apply blur layer with different combinations from Layer > New Layer > Blur > Blur 

![image](https://user-images.githubusercontent.com/16918004/48675737-c351e480-eb82-11e8-94c5-cdbf0eefff9d.png)

For different type of blur we expect variations in Size in format blur-star-{blur type}-{size-x}-{size-y}.sif

We expect,

blur-star-box-0-20.sif
blur-star-box-20-0.sif
blur-star-box-20-20.sif

blur-star-crosshatch-0-20.sif
blur-star-crosshatch-20-0.sif
blur-star-crosshatch-20-20.sif

blur-star-disc-0-20.sif
blur-star-disc-20-0.sif
blur-star-disc-20-20.sif

blur-star-disc-20-20.sif denotes **blur layer** over **star layer** of **type disc** and of **size 20px, 20px**

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#4

**Comment by morevnaproject** [comment]
Done with this PR - https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/27
