### ISSUE TITLE
Radial Blur Layer Test

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#18]
Add more tests for Radial Blur Layer (https://wiki.synfig.org/Radial_Blur_Layer) to sources/layers/radial-blur.

Initially add Star Layer from Layer > New Layer > Geometry > Star

Then apply blur layer with different combinations from Layer > New Layer > Blur > Radial Blur

![](https://user-images.githubusercontent.com/16918004/48675737-c351e480-eb82-11e8-94c5-cdbf0eefff9d.png)

We expect,

blur-star-size-0.sif
blur-star-size-0.1.sif
blur-star-size-0.5.sif
blur-star-size-1.sif
blur-star-size-0-fadeout.sif
blur-star-size-0.1-fadeout.sif
blur-star-size-0.5-fadeout.sif
blur-star-size-1-fadeout.sif

For all tests only the "Blend Method" parameter should be set to "Straight".

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#5

**Comment by morevnaproject** [comment]
Done with https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/28
