### ISSUE TITLE
Conical Gradient Layer Test

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#19]
Add tests for Conical Gradient Layer (https://wiki.synfig.org/Conical_Gradient_Layer) to sources/layers/conical-gradient.

We expect to see the following :)

gradient-conical-black-white.sif
gradient-conical-blue-yellow.sif
gradient-conical-blue-black.sif
gradient-conical-blue-white.sif
gradient-conical-red-black.sif
gradient-conical-red-white.sif
gradient-conical-red-alpha.sif
gradient-conical-black-white-symmetric.sif
gradient-conical-black-white-angle-33.sif
gradient-conical-black-white-origin-20-20.sif

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#6

**Comment by morevnaproject** [comment]
Closed with https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/13
