### ISSUE TITLE
Noise Gradient Layer Tests

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#20]
Add tests for Noise Gradient Layer (https://wiki.synfig.org/Noise_Gradient_Layer) to sources/layers/noise-gradient.

We expect to see :)

gradient-noise-black-white.sif
gradient-noise-blue-yellow.sif
gradient-noise-blue-black.sif
gradient-noise-blue-white.sif
gradient-noise-red-black.sif
gradient-noise-red-white.sif
gradient-noise-red-alpha.sif
gradient-noise-black-white-size-0-0.sif
gradient-noise-black-white-size-1-1.sif
gradient-noise-black-white-size-1-60.sif
gradient-noise-black-white-size-60-1.sif
gradient-noise-black-white-size-5-200.sif
gradient-noise-black-white-size-200-5.sif
gradient-noise-black-white-size-20-20.sif
gradient-noise-black-white-size-200-200.sif
gradient-noise-black-white-center-20-20.sif
gradient-noise-black-white-interpolation-nearestneighbor.sif
gradient-noise-black-white-interpolation-linear.sif
gradient-noise-black-white-interpolation-cosine.sif
gradient-noise-black-white-interpolation-spline.sif
gradient-noise-black-white-interpolation-cubuc.sif
gradient-noise-black-white-detail-0.sif
gradient-noise-black-white-detail-1.sif
gradient-noise-black-white-detail-2.sif
gradient-noise-black-white-detail-3.sif
gradient-noise-black-white-detail-10.sif
gradient-noise-black-white-turbulent.sif
gradient-noise-black-white-doalpha.sif
gradient-noise-black-white-supersample.sif

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#7

**Comment by morevnaproject** [comment]
Closed by https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/29
