### ISSUE TITLE
Radial Gradient Layer

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#21]
Add tests for Radial Gradient Layer (https://wiki.synfig.org/Radial_Gradient_Layer) to sources/layers/radial-gradient.

We expect to see :)

gradient-radial-black-white.sif
gradient-radial-blue-yellow.sif
gradient-radial-blue-black.sif
gradient-radial-blue-white.sif
gradient-radial-red-black.sif
gradient-radial-red-white.sif
gradient-radial-red-alpha.sif
gradient-radial-black-white-loop.sif
gradient-radial-black-white-zigzag.sif
gradient-radial-black-white-loop-zigzag.sif

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#8

**Comment by morevnaproject** [comment]
Closed with https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/12
