### ISSUE TITLE
Spiral Gradient Layer

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#22]
Add tests for Spiral Gradient Layer (https://wiki.synfig.org/Spiral_Gradient_Layer) to sources/layers/spiral-gradient.

We expect to see :)

gradient-spiral-black-white.sif
gradient-spiral-blue-yellow.sif
gradient-spiral-blue-black.sif
gradient-spiral-blue-white.sif
gradient-spiral-red-black.sif
gradient-spiral-red-white.sif
gradient-spiral-red-alpha.sif
gadient-spiral-black-white-angle-30.sif
gradient-spiral-black-white-center-20-20.sif
gradient-spiral-black-white-radius-0.sif
gradient-spiral-black-white-radius-1.sif
gradient-spiral-black-white-radius-5.sif
gradient-spiral-black-white-radius-20.sif
gradient-spiral-black-white-radius-60.sif
gradient-spiral-black-white-radius-1000.sif
gradient-spiral-black-white-clockwise.sif

For general requirements on creating tests please make sure to check information here - https://github.com/synfig/synfig-tests-regressions/blob/master/Contributing.md

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#9

**Comment by morevnaproject** [comment]
Done by https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/20
