### ISSUE TITLE
Include synfig studio's icons files to our test suite

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#23]
Synfig studio's icon files are updated at https://github.com/synfig/synfig/tree/master/synfig-studio/images.

A bash script that would automatically update them from latest commit of Synfig's official repository.

We will run this script from time to time to sync icons in https://github.com/synfig/synfig-test-regressions with icon files in https://github.com/synfig/synfig

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#10

**Comment by morevnaproject** [comment]
Closed by https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/19
