### ISSUE TITLE
Convert sifz to sif

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#24]
Include complex examples from https://github.com/synfig/synfig/tree/master/synfig-core/examples

They are saved as "sifz" files, so the task would be to re-save them all to "sif". Possibly, through a script which turns all sifz files to sif.

**Comment by morevnaproject** [comment]
I have changed label for this issue, since "sifz" is just a gzipped "sif" file. ^__^

**Comment by reSHARMA** [comment]
This issue was moved to NJACKWinterOfCode/synfig-tests-regressions#11

**Comment by morevnaproject** [comment]
Closed by https://github.com/NJACKWinterOfCode/synfig-tests-regressions/pull/15
