### ISSUE TITLE
Add more sample files for different layers of synfig.

### ISSUE THREAD

**Issue by reSHARMA** [synfig/synfig-tests-regressions#3]
Synfig have 50+ layers and we need to cover each one for testing the regression in rendering engine.

The layers are listed at https://wiki.synfig.org/Dev:Introduction_to_Layers 

Download synfig version 1.0.2 https://sourceforge.net/projects/synfig/files/releases/1.0.2/ 
Create a sample file featuring the selected layer eg Circle with radius 0 
Save it as .sif

PS: Please make sure to use ".sif" format instead of ".sifz"

Some sample files are already present at https://github.com/synfig/synfig-tests-regressions/tree/master/sources/layers

Edits are taken from @morevnaproject comments, many thanks!

Happy first contribution at synfig :)

**Comment by morevnaproject** [comment]
Technical note: please make sure to use ".sif" format instead of ".sifz", since it is contains plain XML data and allows to track changes (SIFZ format is a gz-compressed SIF). Thank you! ^__^

**Comment by morevnaproject** [comment]
Also, please make sure to use Synfig version 1.0.2 for creating test files - https://sourceforge.net/projects/synfig/files/releases/1.0.2/

**Comment by reSHARMA** [comment]
@morevnaproject I plan to organize a small workshop within 10 days, where each attendee will contribute one sample file to our test suite. Is it fine with you?

**Comment by morevnaproject** [comment]
@reSHARMA That would be absolutely awesome! This would also allow to get more people get familiar with Synfig! Please let me know as soon as the workshop date will be defined - so I will get prepared for processing massive incoming of issues. ^__^

**Comment by reSHARMA** [comment]
@morevnaproject Awesome, I've floated a Google form which will give us idea about number of people interested and idea about selecting date for the same :) I've set it's deadline till 10th nov.

**Comment by morevnaproject** [comment]
Great! Thank you!

**Comment by reSHARMA** [comment]
@morevnaproject can we chat somewhere mail / irc?

**Comment by morevnaproject** [comment]
@reSHARMA please check your mailbox - I have mailed to you. ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject how many are left now?

**Comment by morevnaproject** [comment]
Hi! Here is a document with a list of layers - https://docs.google.com/document/d/15ri8uJMnzqdTz9aUES5ID9Yn5le3k9aFgZclLxCi6WI/edit?usp=sharing

The names marked with green indicate that they have test files.
The ones marked with black are still have no tests.

**Comment by morevnaproject** [comment]
The issue is moved to https://gitlab.com/synfig/synfig-tests/issues/3
